ci: test

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -6,7 +6,8 @@ env:
   AWS_REGION: 'ap-northeast-2'
   WORKING_DIR: './terraform'
   EC2_INSTANCE_NAME: 'kakao-friend-list-server'
-  EC2_KEY_PAIR_NAME: 'terraform_key_pair'
+  EC2_KEY_PAIR_NAME: 'terraform_key_pair_2'
+  SECURITY_GROUP_NAME: 'my-server-sg'
 
 jobs:
   terraform:
@@ -40,34 +41,63 @@ jobs:
         run: |
           if aws ec2 describe-key-pairs --key-names "${{ env.EC2_KEY_PAIR_NAME }}" >/dev/null 2>&1; then
             echo "Key pair exists."
-            echo "KEY_PARI_EXISTS=true" >> $GITHUB_OUTPUT            
+            echo "KEY_PARI_EXISTS=true" >> $GITHUB_OUTPUT
           else
-            echo "Key pair does not exist."            
+            echo "Key pair does not exist."
             echo "KEY_PARI_EXISTS=false" >> $GITHUB_OUTPUT
           fi
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3
-
       - name: Terraform Init
         run: terraform init
-        working-directory: ${{ env.WORKING_DIR }}
+        working-directory: ${{ env.WORKING_DIR }}/key_pair
 
       - name: Terraform Format
         run: terraform fmt -check
-        working-directory: ${{ env.WORKING_DIR }}
+        working-directory: ${{ env.WORKING_DIR }}/key_pair
 
       - name: Terraform Validate
         if: success() || failure()
         run: terraform validate -no-color
-        working-directory: ${{ env.WORKING_DIR }}
+        working-directory: ${{ env.WORKING_DIR }}/key_pair
 
       - name: Terraform Plan
         if: steps.check-instance.outputs.INSTANCE_EXISTS == ''
-        run: terraform plan -no-color -var="ec2_instance_name=${{ env.EC2_INSTANCE_NAME }}"
-        working-directory: ${{ env.WORKING_DIR }}
+        run: terraform plan -no-color -var="key_pair_name=${{ env.EC2_KEY_PAIR_NAME }}"
+        working-directory: ${{ env.WORKING_DIR }}/key_pair
 
       - name: Terraform Apply
         if: steps.check-instance.outputs.INSTANCE_EXISTS == ''
-        run: terraform apply -auto-approve -var="ec2_instance_name=${{ env.EC2_INSTANCE_NAME }}"
-        working-directory: ${{ env.WORKING_DIR }}
+        run: terraform apply -auto-approve -var="key_pair_name=${{ env.EC2_KEY_PAIR_NAME }}"
+        working-directory: ${{ env.WORKING_DIR }}/key_pair
+
+      # - name: Get Security Group ID
+      #   id: sg_id
+      #   run: |
+      #     SG_ID=$(aws ec2 describe-security-groups --query "SecurityGroups[?GroupName=='${{ env.SECURITY_GROUP_NAME }}'].GroupId" --output text)
+      #     echo "SGID=${SGID}" >> $GITHUB_OUTPUT
+
+      # - name: Setup Terraform
+      #   uses: hashicorp/setup-terraform@v3
+
+      # - name: Terraform Init
+      #   run: terraform init
+      #   working-directory: ${{ env.WORKING_DIR }}
+
+      # - name: Terraform Format
+      #   run: terraform fmt -check
+      #   working-directory: ${{ env.WORKING_DIR }}
+
+      # - name: Terraform Validate
+      #   if: success() || failure()
+      #   run: terraform validate -no-color
+      #   working-directory: ${{ env.WORKING_DIR }}
+
+      # - name: Terraform Plan
+      #   if: steps.check-instance.outputs.INSTANCE_EXISTS == ''
+      #   run: terraform plan -no-color -var="ec2_instance_name=${{ env.EC2_INSTANCE_NAME }}"
+      #   working-directory: ${{ env.WORKING_DIR }}
+
+      # - name: Terraform Apply
+      #   if: steps.check-instance.outputs.INSTANCE_EXISTS == ''
+      #   run: terraform apply -auto-approve -var="ec2_instance_name=${{ env.EC2_INSTANCE_NAME }}"
+      #   working-directory: ${{ env.WORKING_DIR }}
