ci: test

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -8,14 +8,14 @@ on:
 env:
   AWS_REGION: 'ap-northeast-2'
   WORKING_DIR: './terraform'
-  EC2_INSTANCE_NAME: 'kakao-friend-list-server-3'
+  EC2_INSTANCE_NAME: 'kakao-friend-list-server-2'
   EC2_KEY_PAIR_NAME: 'terraform_key_pair'
   SECURITY_GROUP_NAME: 'my-server-sg'
   SECURITY_GROUP_ID: ''
   VPC_TAG_NAME: 'my-vpc'
   VPC_ID: ''
   VPC_SUBNET_TAG_NAME: 'my-subnet'
-  EC2_I_AM_ROLE_NAME: 'ec2-code-deploy-role'
+  EC2_I_AM_ROLE_NAME: 'ec2-code-deploy-role-2'
 
 jobs:
   terraform:
@@ -142,6 +142,36 @@ jobs:
         run: |
           SG_ID=$(aws ec2 describe-security-groups --query "SecurityGroups[?GroupName=='${{ env.SECURITY_GROUP_NAME }}'].GroupId" --output text)
           echo SECURITY_GROUP_ID=$SG_ID >> $GITHUB_ENV
+      
+      - name: Check EC2 IAM Role Existence
+        id: check_iam_role
+        run: |
+          ROLE_EXISTS=$(aws iam get-role --role-name "${{ env.EC2_I_AM_ROLE_NAME }}" 2>&1 || echo "not found")
+          if [[ "$ROLE_EXISTS" == *"not found"* ]]; then
+            echo "IAM_ROLE_EXISTS=false" >> $GITHUB_OUTPUT
+          else
+            echo "IAM_ROLE_EXISTS=true" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Terraform Init for IAM Role
+        if: steps.check_iam_role.outputs.IAM_ROLE_EXISTS == 'false'
+        run: terraform init
+        working-directory: ${{ env.WORKING_DIR }}/iam_role
+
+      - name: Terraform Validate for IAM Role
+        if: steps.check_iam_role.outputs.IAM_ROLE_EXISTS == 'false'
+        run: terraform validate -no-color
+        working-directory: ${{ env.WORKING_DIR }}/iam_role
+
+      - name: Terraform Plan for IAM Role
+        if: steps.check_iam_role.outputs.IAM_ROLE_EXISTS == 'false'
+        run: terraform plan -no-color -var="role_name=${{ env.EC2_I_AM_ROLE_NAME }}"
+        working-directory: ${{ env.WORKING_DIR }}/iam_role
+
+      - name: Terraform Apply for IAM Role
+        if: steps.check_iam_role.outputs.IAM_ROLE_EXISTS == 'false'
+        run: terraform apply -auto-approve -var="role_name=${{ env.EC2_I_AM_ROLE_NAME }}"
+        working-directory: ${{ env.WORKING_DIR }}/iam_role
 
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
